# Generated by Django 5.2.11 on 2026-02-20 22:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Player',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=50, verbose_name='Imię')),
                ('last_name', models.CharField(max_length=50, verbose_name='Nazwisko')),
                ('nickname', models.CharField(blank=True, max_length=50, null=True, unique=True, verbose_name='Pseudonim')),
                ('joined_date', models.DateField(auto_now_add=True, verbose_name='Data dołączenia')),
                ('is_active', models.BooleanField(default=True, verbose_name='Aktywny')),
            ],
            options={
                'verbose_name': 'Gracz',
                'verbose_name_plural': 'Gracze',
                'ordering': ['last_name', 'first_name'],
            },
        ),
        migrations.CreateModel(
            name='EloMatch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('result', models.CharField(choices=[('A', 'Wygrywa Gracz A'), ('B', 'Wygrywa Gracz B'), ('D', 'Remis')], max_length=1, verbose_name='Wynik')),
                ('date', models.DateField(verbose_name='Data meczu')),
                ('notes', models.TextField(blank=True, verbose_name='Uwagi')),
                ('player_a', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='matches_as_a', to='laczkerscup.player', verbose_name='Gracz A')),
                ('player_b', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='matches_as_b', to='laczkerscup.player', verbose_name='Gracz B')),
            ],
            options={
                'verbose_name': 'Mecz ELO',
                'verbose_name_plural': 'Mecze ELO',
                'ordering': ['-date', '-id'],
            },
        ),
        migrations.CreateModel(
            name='EloHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rating_before', models.IntegerField(verbose_name='Rating przed')),
                ('delta', models.IntegerField(verbose_name='Zmiana')),
                ('rating_after', models.IntegerField(verbose_name='Rating po')),
                ('match', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='laczkerscup.elomatch', verbose_name='Mecz')),
                ('player', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='laczkerscup.player', verbose_name='Gracz')),
            ],
            options={
                'verbose_name': 'Historia ELO',
                'verbose_name_plural': 'Historia ELO',
                'ordering': ['match__date', 'match__id'],
            },
        ),
    ]
