# Generated by Django 5.2.11 on 2026-02-24 21:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('laczkerscup', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='LosowanieELO',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nazwa', models.CharField(blank=True, max_length=100, verbose_name='Nazwa')),
                ('data', models.DateTimeField(auto_now_add=True, verbose_name='Data utworzenia')),
                ('liczba_kolejek', models.PositiveSmallIntegerField(verbose_name='Liczba kolejek')),
            ],
            options={
                'verbose_name': 'Losowanie ELO',
                'verbose_name_plural': 'Losowania ELO',
                'ordering': ['-data'],
            },
        ),
        migrations.CreateModel(
            name='MeczLosowania',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kolejka', models.PositiveSmallIntegerField(verbose_name='Kolejka')),
                ('czy_bye', models.BooleanField(default=False, verbose_name='BYE')),
                ('gracz_a', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='losowania_jako_a', to='laczkerscup.player')),
                ('gracz_b', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='losowania_jako_b', to='laczkerscup.player')),
                ('losowanie', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mecze', to='laczkerscup.losowanieelo')),
            ],
            options={
                'ordering': ['kolejka', 'id'],
            },
        ),
        migrations.CreateModel(
            name='UczestnikLosowania',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('koszyk', models.CharField(choices=[('R', 'Rozstawiony'), ('N', 'Nierozstawiony')], max_length=1)),
                ('gracz', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='laczkerscup.player')),
                ('losowanie', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='uczestnicy', to='laczkerscup.losowanieelo')),
            ],
            options={
                'ordering': ['koszyk', 'gracz__last_name'],
                'unique_together': {('losowanie', 'gracz')},
            },
        ),
    ]
