# Generated by Django 5.2.11 on 2026-02-28 20:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('laczkerscup', '0002_losowanieelo_meczlosowania_uczestniklosowania'),
    ]

    operations = [
        migrations.CreateModel(
            name='Etap',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nazwa', models.CharField(max_length=100, verbose_name='Nazwa')),
                ('typ', models.CharField(choices=[('grupowy', 'Grupowy'), ('pucharowy', 'Pucharowy')], max_length=20, verbose_name='Typ')),
                ('poziom', models.PositiveSmallIntegerField(help_text='Określa kolejność etapów: 1 = faza grupowa, 2 = ćwierćfinały, 3 = finał itp.', verbose_name='Poziom')),
            ],
            options={
                'verbose_name': 'Etap',
                'verbose_name_plural': 'Etapy',
                'ordering': ['turniej', 'poziom', 'nazwa'],
            },
        ),
        migrations.CreateModel(
            name='Turniej',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nazwa', models.CharField(max_length=100, verbose_name='Nazwa')),
                ('data_start', models.DateField(blank=True, null=True, verbose_name='Data rozpoczęcia')),
                ('data_koniec', models.DateField(blank=True, null=True, verbose_name='Data zakończenia')),
                ('opis', models.TextField(blank=True, verbose_name='Opis')),
            ],
            options={
                'verbose_name': 'Turniej',
                'verbose_name_plural': 'Turnieje',
                'ordering': ['-data_start'],
            },
        ),
        migrations.CreateModel(
            name='Mecz',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gole_a', models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='Gole A')),
                ('gole_b', models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='Gole B')),
                ('zolte_a', models.PositiveSmallIntegerField(default=0, verbose_name='Żółte kartki A')),
                ('zolte_b', models.PositiveSmallIntegerField(default=0, verbose_name='Żółte kartki B')),
                ('czerwone_a', models.PositiveSmallIntegerField(default=0, verbose_name='Czerwone kartki A')),
                ('czerwone_b', models.PositiveSmallIntegerField(default=0, verbose_name='Czerwone kartki B')),
                ('zwyciezca', models.CharField(blank=True, choices=[('A', 'Gracz A'), ('B', 'Gracz B'), ('remis', 'Remis')], max_length=10, null=True, verbose_name='Zwycięzca')),
                ('status', models.CharField(choices=[('zaplanowany', 'Zaplanowany'), ('rozegrany', 'Rozegrany'), ('wolny_los', 'Wolny los')], default='zaplanowany', max_length=20, verbose_name='Status')),
                ('data', models.DateField(blank=True, null=True, verbose_name='Data meczu')),
                ('opis', models.TextField(blank=True, verbose_name='Opis / notatki')),
                ('etap', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='mecze', to='laczkerscup.etap', verbose_name='Etap')),
                ('gracz_a', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='mecze_jako_a', to='laczkerscup.player', verbose_name='Gracz A')),
                ('gracz_b', models.ForeignKey(blank=True, help_text='Zostaw puste dla wolnego losu', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='mecze_jako_b', to='laczkerscup.player', verbose_name='Gracz B')),
                ('turniej', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='mecze', to='laczkerscup.turniej', verbose_name='Turniej')),
            ],
            options={
                'verbose_name': 'Mecz',
                'verbose_name_plural': 'Mecze',
                'ordering': ['turniej', 'etap__poziom', 'data'],
            },
        ),
        migrations.AddField(
            model_name='etap',
            name='turniej',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='etapy', to='laczkerscup.turniej', verbose_name='Turniej'),
        ),
        migrations.CreateModel(
            name='WystepGracza',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gole_strzelone', models.PositiveSmallIntegerField(default=0)),
                ('gole_stracone', models.PositiveSmallIntegerField(default=0)),
                ('zolte_kartki', models.PositiveSmallIntegerField(default=0)),
                ('czerwone_kartki', models.PositiveSmallIntegerField(default=0)),
                ('punkty', models.PositiveSmallIntegerField(default=0)),
                ('etap', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='wystepy', to='laczkerscup.etap')),
                ('gracz', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='wystepy', to='laczkerscup.player')),
                ('mecz', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='wystepy', to='laczkerscup.mecz')),
                ('przeciwnik', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='wystepy_jako_przeciwnik', to='laczkerscup.player')),
                ('turniej', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='wystepy', to='laczkerscup.turniej')),
            ],
            options={
                'verbose_name': 'Występ gracza',
                'verbose_name_plural': 'Występy graczy',
                'ordering': ['turniej', 'etap__poziom', 'mecz'],
            },
        ),
        migrations.CreateModel(
            name='UczestnikTurnieju',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('zespol', models.CharField(max_length=100, verbose_name='Zespół')),
                ('gracz', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='laczkerscup.player', verbose_name='Gracz')),
                ('turniej', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='uczestnicy', to='laczkerscup.turniej', verbose_name='Turniej')),
            ],
            options={
                'verbose_name': 'Uczestnik turnieju',
                'verbose_name_plural': 'Uczestnicy turnieju',
                'ordering': ['gracz__last_name'],
                'unique_together': {('turniej', 'gracz')},
            },
        ),
    ]
