# Generated by Django 5.2.11 on 2026-02-28 22:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('laczkerscup', '0003_etap_turniej_mecz_etap_turniej_wystepgracza_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='etap',
            name='obrazek',
            field=models.ImageField(blank=True, help_text='Wyświetlany przy etapach pucharowych. Zostaw puste = placeholder.', null=True, upload_to='drabinki/', verbose_name='Drabinka (obrazek)'),
        ),
    ]
