# Generated by Django 5.2.11 on 2026-03-07 19:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('laczkerscup', '0004_etap_obrazek'),
    ]

    operations = [
        migrations.CreateModel(
            name='SzwajcarKolejka',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numer', models.PositiveSmallIntegerField(verbose_name='Numer kolejki')),
                ('data_utworzenia', models.DateTimeField(auto_now_add=True)),
                ('turniej', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='szwajcar_kolejki', to='laczkerscup.turniej')),
            ],
            options={
                'verbose_name': 'Kolejka szwajcarska',
                'verbose_name_plural': 'Kolejki szwajcarskie',
                'ordering': ['turniej', 'numer'],
                'unique_together': {('turniej', 'numer')},
            },
        ),
        migrations.CreateModel(
            name='SzwajcarPara',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gracz_a', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='szwajcar_jako_a', to='laczkerscup.player')),
                ('gracz_b', models.ForeignKey(blank=True, help_text='Null = wolny los dla gracza A', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='szwajcar_jako_b', to='laczkerscup.player')),
                ('kolejka', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pary', to='laczkerscup.szwajcarkolejka')),
            ],
            options={
                'ordering': ['kolejka', 'id'],
            },
        ),
    ]
