# Generated by Django 5.2.11 on 2026-03-22 12:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('laczkerscup', '0005_szwajcarkolejka_szwajcarpara'),
    ]

    operations = [
        migrations.AddField(
            model_name='uczestnikturnieju',
            name='ulubiony_klub',
            field=models.CharField(blank=True, default='', help_text='Zostaw puste jeśli gracz nie kibicuje żadnemu klubowi.', max_length=100, verbose_name='Ulubiony klub'),
        ),
    ]
