# Generated by Django 5.2.11 on 2026-03-25 21:05

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('laczkerscup', '0006_uczestnikturnieju_ulubiony_klub'),
    ]

    operations = [
        migrations.AddField(
            model_name='turniej',
            name='notka',
            field=ckeditor.fields.RichTextField(blank=True, default='', help_text='Artykuł opisujący turniej — wyświetlany na osobnej podstronie.', verbose_name='Notka o turnieju'),
        ),
        migrations.AddField(
            model_name='turniej',
            name='zdjecie',
            field=models.ImageField(blank=True, help_text='Opcjonalne zdjęcie wyświetlane w notce turnieju.', null=True, upload_to='turnieje/', verbose_name='Zdjęcie'),
        ),
    ]
