# Generated by Django 5.2.11 on 2026-03-25 22:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('laczkerscup', '0007_turniej_notka_turniej_zdjecie'),
    ]

    operations = [
        migrations.CreateModel(
            name='WynikTurnieju',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('zwycięski_klub', models.CharField(blank=True, default='', max_length=100, verbose_name='Zwycięski klub')),
                ('kosiarz', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='laczkerscup.player', verbose_name='Kosiarz')),
                ('krol_strzelcow', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='laczkerscup.player', verbose_name='Król strzelców')),
                ('miejsce_1', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='laczkerscup.player', verbose_name='1. miejsce')),
                ('miejsce_2', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='laczkerscup.player', verbose_name='2. miejsce')),
                ('miejsce_3', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='laczkerscup.player', verbose_name='3. miejsce')),
                ('miejsce_ostatnie', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='laczkerscup.player', verbose_name='Ostatnie miejsce')),
                ('murarz', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='laczkerscup.player', verbose_name='Murarz')),
                ('turniej', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='wynik', to='laczkerscup.turniej', verbose_name='Turniej')),
            ],
            options={
                'verbose_name': 'Wynik turnieju (typer)',
                'verbose_name_plural': 'Wyniki turniejów (typer)',
            },
        ),
        migrations.CreateModel(
            name='TypTurnieju',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('zwycięski_klub', models.CharField(blank=True, default='', max_length=100, verbose_name='Typ: Zwycięski klub')),
                ('gracz', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='typy', to='laczkerscup.player', verbose_name='Gracz typujący')),
                ('kosiarz', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='laczkerscup.player', verbose_name='Typ: Kosiarz')),
                ('krol_strzelcow', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='laczkerscup.player', verbose_name='Typ: Król strzelców')),
                ('miejsce_1', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='laczkerscup.player', verbose_name='Typ: 1. miejsce')),
                ('miejsce_2', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='laczkerscup.player', verbose_name='Typ: 2. miejsce')),
                ('miejsce_3', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='laczkerscup.player', verbose_name='Typ: 3. miejsce')),
                ('miejsce_ostatnie', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='laczkerscup.player', verbose_name='Typ: Ostatnie miejsce')),
                ('murarz', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='laczkerscup.player', verbose_name='Typ: Murarz')),
                ('turniej', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='typy', to='laczkerscup.turniej', verbose_name='Turniej')),
            ],
            options={
                'verbose_name': 'Typ gracza',
                'verbose_name_plural': 'Typy graczy',
                'ordering': ['turniej', 'gracz__last_name'],
                'unique_together': {('turniej', 'gracz')},
            },
        ),
    ]
