# Generated by Django 5.2.11 on 2026-03-26 19:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('laczkerscup', '0008_wynikturnieju_typturnieju'),
    ]

    operations = [
        migrations.AddField(
            model_name='etap',
            name='przenies_punkty_z',
            field=models.ForeignKey(blank=True, help_text='Punkty z wybranego etapu zostaną dodane do punktów startowych w tym etapie. Zostaw puste = start od 0. Używaj tylko dla etapów grupowych.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='laczkerscup.etap', verbose_name='Przenieś punkty z etapu'),
        ),
    ]
