# Generated by Django 5.2.11 on 2026-03-26 19:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('laczkerscup', '0009_etap_przenies_punkty_z'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='etap',
            name='przenies_punkty_z',
        ),
        migrations.AddField(
            model_name='etap',
            name='sumuj_punkty_z_poprzednich',
            field=models.BooleanField(default=False, help_text='Jeśli zaznaczone, punkty gracza ze wszystkich etapów grupowych o niższym poziomie w tym turnieju zostaną dodane jako punkty startowe.', verbose_name='Sumuj punkty z poprzednich poziomów'),
        ),
    ]
