# Generated by Django 5.2.11 on 2026-04-01 20:51

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('laczkerscup', '0010_remove_etap_przenies_punkty_z_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='etap',
            options={'ordering': ['turniej', 'poziom', 'data_utworzenia'], 'verbose_name': 'Etap', 'verbose_name_plural': 'Etapy'},
        ),
        migrations.AddField(
            model_name='etap',
            name='data_utworzenia',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now, help_text='Używana do sortowania etapów na tym samym poziomie.', verbose_name='Data utworzenia'),
            preserve_default=False,
        ),
    ]
