# Generated by Django 5.2.11 on 2026-06-03 21:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('laczkerscup', '0011_alter_etap_options_etap_data_utworzenia'),
    ]

    operations = [
        migrations.AddField(
            model_name='szwajcarkolejka',
            name='zaimportowana',
            field=models.BooleanField(default=False, help_text='Czy pary z tej kolejki zostały zaimportowane jako mecze do turnieju.', verbose_name='Zaimportowana'),
        ),
    ]
