# Generated by Django 5.2.11 on 2026-06-03 21:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('laczkerscup', '0012_szwajcarkolejka_zaimportowana'),
    ]

    operations = [
        migrations.AddField(
            model_name='losowanieelo',
            name='turniej',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='losowania', to='laczkerscup.turniej', verbose_name='Turniej'),
        ),
    ]
